Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2018-10, with the labels that each got.

#633 From private repo
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/configure-policy-delete-reorder.md
  Azure-RMSDocs/configure-policy-settings.md
  Azure-RMSDocs/configure-servers-rms-connector.md
  Azure-RMSDocs/deployment-roadmap.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/index.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/media/protection-only-mode.png
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/client-protection-only-mode.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/client-view-use-files.md
  Azure-RMSDocs/what-is-information-protection.md
  mip/develop/concept-async-observers-protection-cpp.md
  mip/develop/concept-authentication-cpp.md
  mip/develop/media/quick-app-initialization-cpp/add-nuget-package.png
  mip/develop/overview.md
  mip/develop/quick-app-initialization-cpp.md
  mip/develop/quick-file-list-labels-cpp.md
  mip/develop/quick-file-set-get-label-cpp.md
  mip/develop/setup-configure-mip.md
  mip/develop/toc.yml
Labels: do-not-merge

#634 From private repo
  Azure-RMSDocs/configure-usage-rights.md
  Azure-RMSDocs/office-apps-services-support.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
  mip/develop/quick-app-initialization-cpp.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#635 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#636 From private repo
  Azure-RMSDocs/plan-implement-tenant-key.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#637 From private repo
  Azure-RMSDocs/configure-super-users.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#639 From private repo
  Azure-RMSDocs/configure-super-users.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#641 From private repo
  Azure-RMSDocs/configure-super-users.md
  mip/docfx.json
Labels: Change sent to author, do-not-merge, information-protection/svc

#642 From private repo
  Azure-RMSDocs/activate-azure.md
  Azure-RMSDocs/configure-policy-add-remove-label.md
  Azure-RMSDocs/configure-policy-change-label.md
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/configure-policy-delete-reorder.md
  Azure-RMSDocs/configure-policy-languages.md
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy-new-label.md
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/configure-policy-scope.md
  Azure-RMSDocs/configure-policy-settings.md
  Azure-RMSDocs/configure-policy-templates.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/infoprotect-tutorial-step1.md
  Azure-RMSDocs/infoprotect-tutorial-step2.md
  Azure-RMSDocs/migrate-portal.md
  Azure-RMSDocs/office-apps-services-support.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/requirements-applications.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/protected-pdf-readers.md
Labels: Change sent to author, azure/prod, do-not-merge, information-protection/svc

#643 From private repo
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/reports-aip.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#644 From private repo
  Azure-RMSDocs/configure-policy-settings.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#647 From private repo
  Azure-RMSDocs/configure-exo-rules.md
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/rms-client/TOC.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/install-unifiedlabelingclient-app.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#648 From private repo
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#649 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/media/editregistry-scanner.png
Labels: Change sent to author, do-not-merge, information-protection/svc

#650 From private repo
  mip/develop/concept-apis-use-cases.md
  mip/develop/faqs-known-issues.md
  mip/develop/media/concept-apis-use-cases/mip-sdk-components.png
  mip/develop/setup-configure-mip.md
  mip/develop/toc.yml
  mip/include/mip-sdk-platform-support.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#652 typo: Double word "the"
  Azure-RMSDocs/configure-policy.md
Labels: Change sent to author, information-protection/svc, ready-to-merge

#653 typo: Double word "that"
  Azure-RMSDocs/terminology.md
Labels: Change sent to author, information-protection/svc, ready-to-merge

#651 typo: Double word "Size"
  Azure-RMSDocs/Develop/mip/mip-functions.md
Labels: do-not-merge

#656 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#657 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  mip/develop/index.yml
  mip/develop/media/index/kartik-tom-mip-sdk.png
Labels: Change sent to author, do-not-merge, information-protection/svc

#659 From private repo
  Azure-RMSDocs/refresh-templates.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#661 From private repo
  Azure-RMSDocs/configure-policy-protection.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#660 fix typo
  mip/develop/concept-async-observers-protection-cpp.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#662 From private repo
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#664 From private repo
  Azure-RMSDocs/what-is-information-protection.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#665 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#667 From private repo
  Azure-RMSDocs/configure-policy-protection.md
Labels: Change sent to author, do-not-merge, information-protection/svc
