Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2018-06, with the labels that each got.

#523 From private repo
  Azure-RMSDocs/deploy-use/prepare-environment-adrms.md
Labels: Change sent to author, do-not-merge, information-protection

#524 From private repo
  Azure-RMSDocs/get-started/secure-collaboration-documents.md
Labels: Change sent to author, do-not-merge, information-protection

#525 From private repo
  Azure-RMSDocs/deploy-use/activate-service.md
  Azure-RMSDocs/deploy-use/prepare-environment-adrms.md
Labels: Change sent to author, do-not-merge, information-protection

#526 From private repo
  Azure-RMSDocs/deploy-use/configure-usage-rights.md
  Azure-RMSDocs/deploy-use/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection

#527 From private repo
  Azure-RMSDocs/deploy-use/deploy-aip-scanner.md
  Azure-RMSDocs/get-started/faqs.md
Labels: do-not-merge

#528 From private repo
  Azure-RMSDocs/deploy-use/configure-policy-markings.md
  Azure-RMSDocs/plan-design/migrate-from-ad-rms-phase4.md
  Azure-RMSDocs/rms-client/client-deployment-notes.md
Labels: do-not-merge

#529 From private repo
  Azure-RMSDocs/deploy-use/configure-usage-rights.md
Labels: Change sent to author, do-not-merge, information-protection

#530 From private repo
  Azure-RMSDocs/deploy-use/migrate-portal.md
Labels: do-not-merge

#531 From private repo
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
Labels: Change sent to author, information-protection

#532 From private repo
  Azure-RMSDocs/deploy-use/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
Labels: Change sent to author, do-not-merge, information-protection

#533 From private repo
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection

#534 From private repo
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
Labels: do-not-merge

#535 From private repo
  Azure-RMSDocs/deploy-use/configure-policy-protection.md
  Azure-RMSDocs/get-started/secure-collaboration-documents.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
Labels: Change sent to author, do-not-merge, information-protection

#536 From private repo
  Azure-RMSDocs/deploy-use/prepare-environment-adrms.md
  Azure-RMSDocs/plan-design/migrate-from-ad-rms-phase4.md
Labels: Change sent to author, do-not-merge, information-protection

#537 From private repo
  Azure-RMSDocs/deploy-use/deploy-aip-scanner.md
Labels: Change sent to author, do-not-merge, information-protection

#538 From private repo
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
Labels: Change sent to author, do-not-merge, information-protection

#539 From private repo
  Azure-RMSDocs/deploy-use/activate-service.md
  Azure-RMSDocs/deploy-use/deploy-aip-scanner.md
  Azure-RMSDocs/get-started/faqs.md
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection

#541 From private repo
  Azure-RMSDocs/plan-design/plan-implement-tenant-key.md
  Azure-RMSDocs/rms-client/client-track-revoke.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection

#514 Change on cmdlet names from Super User Group management
  Azure-RMSDocs/deploy-use/configure-super-users.md
Labels: Change sent to author, information-protection, ready-to-merge

#543 From private repo
  Azure-RMSDocs/deploy-use/activate-service.md
  Azure-RMSDocs/deploy-use/prepare-environment-adrms.md
  Azure-RMSDocs/docfx.json
  Azure-RMSDocs/plan-design/plan-implement-tenant-key.md
  Azure-RMSDocs/rms-client/upgrade-client-app.md
Labels: Change sent to author, do-not-merge, information-protection

#545 From private repo
  Azure-RMSDocs/deploy-use/activate-service.md
  Azure-RMSDocs/deploy-use/prepare-environment-adrms.md
Labels: do-not-merge
