Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2018-04, with the labels that each got.

#480 From private repo
  Azure-RMSDocs/get-started/faqs.md
Labels: Change sent to author, do-not-merge, information-protection

#481 From private repo
  Azure-RMSDocs/get-started/requirements.md
Labels: Change sent to author, do-not-merge, information-protection

#482 From private repo
  Azure-RMSDocs/rms-client/client-deployment-notes.md
Labels: Change sent to author, do-not-merge, information-protection

#483 From private repo
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: do-not-merge

#484 From private repo
  Azure-RMSDocs/deploy-use/configure-usage-rights.md
  Azure-RMSDocs/understand-explore/how-does-it-work.md
Labels: do-not-merge

#485 From private repo
  Azure-RMSDocs/deploy-use/deploy-aip-scanner.md
  Azure-RMSDocs/media/infoprotect-scanner.png
Labels: Change sent to author, do-not-merge, information-protection

#486 From private repo
  Azure-RMSDocs/deploy-use/configure-exchange-with-imported-tpd.md
Labels: Change sent to author, do-not-merge, information-protection

#487 From private repo
  Azure-RMSDocs/plan-design/migrate-from-ad-rms-phase3.md
  Azure-RMSDocs/understand-explore/rms-for-individuals.md
Labels: Change sent to author, do-not-merge, information-protection

#488 From private repo
  Azure-RMSDocs/deploy-use/configure-policy-classification.md
Labels: Change sent to author, do-not-merge, information-protection

#489 From private repo
  Azure-RMSDocs/deploy-use/administer-powershell.md
  Azure-RMSDocs/deploy-use/install-powershell.md
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
Labels: Change sent to author, information-protection

#490 From private repo
  .openpublishing.publish.config.json
  Azure-RMSDocs/house-rules.md
  LICENSE
  Microsoft-MIPDocs/docfx.json
Labels: Change sent to author, do-not-merge, information-protection

#492 From private repo
  Azure-RMSDocs/Develop/mip/TOC.md
  Azure-RMSDocs/Develop/mip/docfx.json
  Azure-RMSDocs/bread/toc.yml
  Azure-RMSDocs/docfx.json
Labels: Change sent to author, do-not-merge

#493 From private repo
  Azure-RMSDocs/bread/house-rules.md
  Azure-RMSDocs/bread/toc.yml
  Azure-RMSDocs/docfx.json
Labels: Change sent to author, do-not-merge, information-protection

#494 From private repo
  Azure-RMSDocs/bread/house-rules.md
  Azure-RMSDocs/bread/toc.yml
Labels: do-not-merge

#495 From private repo
  Azure-RMSDocs/deploy-use/TOC.md
  Azure-RMSDocs/deploy-use/configure-policy-add-remove-label.md
  Azure-RMSDocs/deploy-use/configure-policy-change-label.md
  Azure-RMSDocs/deploy-use/configure-policy-classification.md
  Azure-RMSDocs/deploy-use/configure-policy-delete-reorder.md
  Azure-RMSDocs/deploy-use/configure-policy-languages.md
  Azure-RMSDocs/deploy-use/configure-policy-markings.md
  Azure-RMSDocs/deploy-use/configure-policy-new-label.md
  Azure-RMSDocs/deploy-use/configure-policy-protection.md
  Azure-RMSDocs/deploy-use/configure-policy-scope.md
  Azure-RMSDocs/deploy-use/configure-policy-settings.md
  Azure-RMSDocs/deploy-use/configure-policy-templates.md
  Azure-RMSDocs/deploy-use/configure-policy.md
  Azure-RMSDocs/deploy-use/install-powershell.md
  Azure-RMSDocs/deploy-use/migrate-portal.md
  Azure-RMSDocs/get-started/infoprotect-tutorial-step1.md
  Azure-RMSDocs/get-started/infoprotect-tutorial-step2.md
  Azure-RMSDocs/get-started/requirements-applications.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection

#497 From private repo
  Azure-RMSDocs/deploy-use/configure-adrms-restrictions.md
  Azure-RMSDocs/deploy-use/configure-office365.md
Labels: Change sent to author, do-not-merge, information-protection

#498 From private repo
  Azure-RMSDocs/deploy-use/configure-policy-protection.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
Labels: Change sent to author, do-not-merge, information-protection

#499 From private repo
  Azure-RMSDocs/get-started/requirements-applications.md
  Azure-RMSDocs/get-started/requirements-azure-ad.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
Labels: do-not-merge

#500 From private repo
  Azure-RMSDocs/deploy-use/configure-policy-scope.md
Labels: Change sent to author, do-not-merge, information-protection
