Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2018-08, with the labels that each got.

#572 From private repo
  Azure-RMSDocs/deploy-use/configure-policy.md
Labels: Change sent to author, do-not-merge, information-protection

#569 Grammar updates for clarity
  Azure-RMSDocs/understand-explore/what-is-information-protection.md
Labels: Change sent to author, information-protection, ready-to-merge

#575 From private repo
  .openpublishing.redirection.json
  Azure-RMSDocs/develop/security-guidelines.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/client-classify-protect.md
  Azure-RMSDocs/rms-client/client-classify.md
  Azure-RMSDocs/rms-client/client-protection-only-mode.md
  Azure-RMSDocs/rms-client/client-remove-label-protection.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/client-view-use-files.md
  Azure-RMSDocs/rms-client/configure-fci.md
  Azure-RMSDocs/rms-client/sharing-app-admin-guide.md
  Azure-RMSDocs/rms-client/sharing-app-reprotect-files.md
  Azure-RMSDocs/terminology.md
Labels: Change sent to author, do-not-merge, information-protection

#576 From private repo
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection

#578 From private repo
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection

#580 From private repo
  Azure-RMSDocs/configure-policy-classification.md
Labels: Change sent to author, information-protection

#582 From private repo
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/develop/TOC.md
  Azure-RMSDocs/rms-client/TOC.md
Labels: Change sent to author, do-not-merge, information-protection

#585 From private repo
  Azure-RMSDocs/configure-office365.md
Labels: do-not-merge

#586 From private repo
  Azure-RMSDocs/compare-on-premise.md
  Azure-RMSDocs/configure-adrms-restrictions.md
  Azure-RMSDocs/configure-policy-classification.md
Labels: do-not-merge

#589 From private repo
  Azure-RMSDocs/configure-policy-templates.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-remove-label-protection.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#590 From private repo
  Azure-RMSDocs/configure-policy-templates.md
  Azure-RMSDocs/office-apps-services-support.md
  Azure-RMSDocs/plan-implement-tenant-key.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#591 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/requirements.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#592 From private repo
  Azure-RMSDocs/configure-usage-rights.md
  Azure-RMSDocs/requirements.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#593 Update configure-usage-rights.md
  Azure-RMSDocs/configure-usage-rights.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#598 From private repo
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/configure-usage-rights.md
  Azure-RMSDocs/plan-implement-tenant-key.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#601 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/plan-implement-tenant-key.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/client-remove-label-protection.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/client-view-use-files.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#603 From private repo
  Azure-RMSDocs/plan-implement-tenant-key.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#604 From private repo
  Azure-RMSDocs/aka.md
  Azure-RMSDocs/api-support.md
  Azure-RMSDocs/applications-support.md
  Azure-RMSDocs/byok-price-restrictions.md
  Azure-RMSDocs/faqs-rms.md
  Azure-RMSDocs/file-server-support.md
  Azure-RMSDocs/infoprotect-tutorial-step3.md
  Azure-RMSDocs/infoprotect-tutorial-step4.md
  Azure-RMSDocs/requirements-servers.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#605 From private repo
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/operations-customer-managed-tenant-key.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#606 From private repo
  Azure-RMSDocs/activate-office365.md
  Azure-RMSDocs/configure-applications.md
  Azure-RMSDocs/configure-client.md
  Azure-RMSDocs/configure-office-apps.md
  Azure-RMSDocs/configure-usage-rights.md
  Azure-RMSDocs/operations-tenant-key.md
  Azure-RMSDocs/plan-implement-tenant-key.md
  Azure-RMSDocs/rms-client/AIP-client.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-classify.md
  Azure-RMSDocs/rms-client/client-user-guide.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/fci-script.md
  Azure-RMSDocs/rms-client/install-client-app.md
  Azure-RMSDocs/rms-client/mobile-app-faq.md
  Azure-RMSDocs/rms-client/use-client.md
  Azure-RMSDocs/verify.md
Labels: Change sent to author, do-not-merge, information-protection/svc
