Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2018-11, with the labels that each got.

#668 From private repo
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-for-individuals.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#669 From private repo
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-for-individuals.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#670 From private repo
  Azure-RMSDocs/configure-policy-default.md
  Azure-RMSDocs/requirements.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#671 From private repo
  Azure-RMSDocs/TOC.md
  Azure-RMSDocs/azure-rms-problems-it-solves.md
  Azure-RMSDocs/compliance.md
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/configure-policy-default.md
  Azure-RMSDocs/configure-policy-scope.md
  Azure-RMSDocs/configure-policy-settings.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/deployment-roadmap.md
  Azure-RMSDocs/develop/TOC.md
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/how-does-it-work.md
  Azure-RMSDocs/how-to-guides.md
  Azure-RMSDocs/infoprotect-quick-start-tutorial.md
  Azure-RMSDocs/infoprotect-settings-tutorial.md
  Azure-RMSDocs/infoprotect-tutorial-step1.md
  Azure-RMSDocs/infoprotect-tutorial-step2.md
  Azure-RMSDocs/infoprotect-tutorial-step4.md
  Azure-RMSDocs/infoprotect-tutorial-step5.md
  Azure-RMSDocs/media/defaultlabel-word.png
  Azure-RMSDocs/media/defaultsettings-aip-changed.png
  Azure-RMSDocs/media/defaultsettings-aip.png
  Azure-RMSDocs/media/infoprotect-bar-close.png
  Azure-RMSDocs/media/infoprotect-deletelabel-icon.png
  Azure-RMSDocs/media/infoprotect-editlabel-icon.png
  Azure-RMSDocs/media/infoprotect-matchemail-label.png
  Azure-RMSDocs/media/infoprotect-protectbutton-pulldown.png
  Azure-RMSDocs/overview-policy.md
  Azure-RMSDocs/quickstart-findsensitiveinfo.md
  Azure-RMSDocs/quickstart-label-dnf-protectedemail.md
  Azure-RMSDocs/quickstart-label-specificusers.md
  Azure-RMSDocs/quickstart-viewpolicy.md
  Azure-RMSDocs/rms-client/TOC.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/secure-collaboration-documents.md
  Azure-RMSDocs/what-is-azure-rms.md
  Azure-RMSDocs/what-is-information-protection.md
  mip/develop/concept-authentication-acquire-token-ps.md
  mip/develop/concept-authentication-acquire-token-py.md
  mip/develop/concept-authentication-delegate-cpp.md
  mip/develop/faqs-known-issues.md
Labels: do-not-merge

#672 From private repo
  Azure-RMSDocs/infoprotect-quick-start-tutorial.md
  Azure-RMSDocs/migrate-portal.md
  Azure-RMSDocs/quickstart-findsensitiveinfo.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#673 From private repo
  Azure-RMSDocs/azure-rms-problems-it-solves.md
  Azure-RMSDocs/infoprotect-quick-start-tutorial.md
  Azure-RMSDocs/infoprotect-tutorial-step1.md
  Azure-RMSDocs/infoprotect-tutorial-step2.md
  Azure-RMSDocs/infoprotect-tutorial-step4.md
  Azure-RMSDocs/infoprotect-tutorial-step5.md
  Azure-RMSDocs/media/info-protect-policy-default-settings.png
  Azure-RMSDocs/media/info-protect-protection-all-members.png
  Azure-RMSDocs/media/info-protect-protection-reviewer.png
  Azure-RMSDocs/media/info-protect-settings-configuredv2.png
  Azure-RMSDocs/media/step2-configure-condition.png
  Azure-RMSDocs/media/step2-see-condition.png
  Azure-RMSDocs/reports-aip.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#674 From private repo
  mip/develop/concept-auditing-file-cpp.md
  mip/develop/concept-auditing-policy-computeactions-cpp.md
  mip/develop/concept-auditing-policy-cpp.md
  mip/develop/concept-auditing-policy-executionstate-cpp.md
  mip/develop/concept-handler-policy-cpp.md
  mip/develop/toc.yml
  mip/include/mip-sdk-platform-support.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#675 From private repo
  mip/develop/toc.yml
Labels: Change sent to author, do-not-merge

#677 From private repo
  mip/develop/setup-configure-mip.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#678 From private repo
  mip/develop/setup-configure-mip.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#681 From private repo
  Azure-RMSDocs/reports-aip.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#682 From private repo
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#683 typo: convertion -> conversion
  Azure-RMSDocs/develop/linux-c-code-examples.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#684 From private repo
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/faqs-rms.md
  Azure-RMSDocs/infoprotect-quick-start-tutorial.md
  Azure-RMSDocs/infoprotect-settings-tutorial.md
  Azure-RMSDocs/quickstart-label-dnf-protectedemail.md
  Azure-RMSDocs/quickstart-label-specificusers.md
  Azure-RMSDocs/quickstart-viewpolicy.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#686 From private repo
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/migrate-from-ad-rms-phase2.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#688 From private repo
  mip/develop/concept-mip-metadata.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#689 From private repo
  Azure-RMSDocs/Add-AadrmKey.md
  Azure-RMSDocs/deploy-rms-connector.md
  Azure-RMSDocs/generate-tenant-key-in-person.md
  Azure-RMSDocs/generate-tenant-key-internet.md
  Azure-RMSDocs/rms-client/use-client.md
  Azure-RMSDocs/thales-hsm.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#690 From private repo
  Azure-RMSDocs/Add-AadrmKey.md
  Azure-RMSDocs/configure-policy-scope.md
  Azure-RMSDocs/generate-tenant-key-in-person.md
  Azure-RMSDocs/generate-tenant-key-internet.md
  Azure-RMSDocs/thales-hsm.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#691 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#692 From private repo
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#695 From private repo
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  Azure-RMSDocs/byok-price-restrictions.md
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/migrate-hsmkey-to-hsmkey.md
  Azure-RMSDocs/migrate-softwarekey-to-hsmkey.md
  Azure-RMSDocs/plan-implement-tenant-key.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/what-is-azure-rms.md
  mip/breadcrumb/toc.yml
  mip/develop/concept-handler-policy-auditing-cpp.md
  mip/develop/concept-handler-policy-computeactions-cpp.md
  mip/develop/concept-handler-policy-cpp.md
  mip/develop/concept-handler-policy-executionstate-cpp.md
  mip/develop/rc/rc.yml
  mip/develop/setup-configure-mip.md
  mip/develop/toc.yml
Labels: Change sent to author, do-not-merge, information-protection/svc

#696 From private repo
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#697 From private repo
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy-templates.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#698 From private repo
  Azure-RMSDocs/activate-office365.md
Labels: Change sent to author, do-not-merge, information-protection/svc
