Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2019-10, with the labels that each got.

#1040 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/index.yml
  Azure-RMSDocs/infoprotect-oversharing-tutorial.md
  Azure-RMSDocs/infoprotect-quick-start-tutorial.md
  Azure-RMSDocs/infoprotect-settings-tutorial.md
  Azure-RMSDocs/manage-personal-data.md
  Azure-RMSDocs/migrate-portal.md
  Azure-RMSDocs/quickstart-viewpolicy.md
  Azure-RMSDocs/refresh-templates.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: do-not-merge

#1042 From private repo
  Azure-RMSDocs/requirements-applications.md
Labels: Change sent to author, do-not-merge, information-protection/svc, prereqs/subsvc

#1043 From private repo
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/reports-aip.md
Labels: Change sent to author, analytics/subsvc, do-not-merge, information-protection/svc

#1044 Fixed typo (Connnect)
  Azure-RMSDocs/migrate-hsmkey-to-hsmkey.md
Labels: Change sent to author, assessing_(C&L), information-protection/svc, migration/subsvc, ready-to-merge

#1046 From private repo
  Azure-RMSDocs/configure-office365.md
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/configure-policy-default.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy-settings.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/configure-super-users.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/deployment-roadmap.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/office-apps-services-support.md
  Azure-RMSDocs/overview-policy.md
  Azure-RMSDocs/quickstart-findsensitiveinfo.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/aip-clientv2.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
  Azure-RMSDocs/rms-client/clientv2-classify-protect.md
  Azure-RMSDocs/rms-client/clientv2-classify.md
  Azure-RMSDocs/rms-client/clientv2-remove-label-protection.md
  Azure-RMSDocs/rms-client/install-unifiedlabelingclient-app.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1048 From private repo
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v1client/subsvc

#1049 From private repo
  Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1050 From private repo
  Azure-RMSDocs/what-is-information-protection.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1052 Fix link for S/MIME deployment
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v1client/subsvc

#1055 From private repo
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1057 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/requirements-azure-ad.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v1client/subsvc

#1058 From private repo
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v1client/subsvc

#1060 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1062 From private repo
  Azure-RMSDocs/reports-aip.md
Labels: Change sent to author, analytics/subsvc, do-not-merge, information-protection/svc

#1063 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
Labels: Change sent to author, do-not-merge, information-protection/svc, labelmigrate/subsvc
