Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2019-11, with the labels that each got.

#1020 Fixed typo (Aquire)
  Azure-RMSDocs/develop/linux-c-code-examples.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, information-protection/svc

#1065 From private repo
  mip/develop/reference/c/enumerations.md
  mip/develop/reference/c/functions.md
  mip/develop/reference/c/overview.md
  mip/develop/reference/c/structures.md
  mip/develop/toc.yml
Labels: do-not-merge

#1067 From private repo
  Azure-RMSDocs/requirements-applications.md
Labels: Change sent to author, do-not-merge, information-protection/svc, prereqs/subsvc

#1070 From private repo
  Azure-RMSDocs/configure-exo-rules.md
  Azure-RMSDocs/media/aip-exo-rule-ex1.png
  Azure-RMSDocs/what-is-information-protection.md
Labels: do-not-merge

#1071 From private repo
  Azure-RMSDocs/quickstart-findsensitiveinfo.md
  Azure-RMSDocs/what-is-information-protection.md
Labels: Change sent to author, aiplabels/subsvc, do-not-merge, information-protection/svc

#1072 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-templates-with-powershell.md
  Azure-RMSDocs/requirements-client-devices.md
  Azure-RMSDocs/rms-client/mobile-app-faq.md
Labels: do-not-merge

#1073 From private repo
  Azure-RMSDocs/reports-aip.md
Labels: Change sent to author, analytics/subsvc, do-not-merge, information-protection/svc

#1075 From private repo
  Azure-RMSDocs/deploy-aip-scanner-previousversions.md
  Azure-RMSDocs/deploy-aip-scanner.md
Labels: Change sent to author, do-not-merge, information-protection/svc, scanner/subsvc

#1076 From private repo
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1078 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/migrate-from-ad-rms-to-azure-rms.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1079 From private repo
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/media/exchange-rule-for-message-header.png
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  mip/develop/concept-mip-telemetry.md
  mip/develop/toc.yml
  mip/develop/version-release-history.md
Labels: do-not-merge

#1081 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/reports-aip.md
Labels: Change sent to author, analytics/subsvc, do-not-merge, information-protection/svc
