Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2019-09, with the labels that each got.

#1006 From private repo
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
  Azure-RMSDocs/rms-client/clientv2-classify-protect.md
  Azure-RMSDocs/rms-client/clientv2-classify.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/toc.yml
Labels: do-not-merge

#1007 From private repo
  Azure-RMSDocs/decommission-deactivate.md
  Azure-RMSDocs/plan-implement-tenant-key.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1008 From private repo
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1009 Updated for release notes
  Azure-RMSDocs/develop/release-notes-rtm.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1010 Revert "Updated for release notes"
  Azure-RMSDocs/develop/release-notes-rtm.md
Labels: do-not-merge

#1016 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/media/scanner-add-profile.png
  Azure-RMSDocs/media/scanner-rescan-files2.png
  Azure-RMSDocs/media/scanner-scan-now.png
  Azure-RMSDocs/quickstart-findsensitiveinfo.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
  mip/develop/quick-app-adrms.md
  mip/develop/reference/class_mip_computeengine.md
  mip/develop/reference/class_mip_filehandler.md
  mip/develop/reference/class_mip_fileprofile.md
  mip/develop/reference/class_mip_mipcontext.md
  mip/develop/reference/class_mip_policyprofile.md
  mip/develop/reference/class_mip_protectiondescriptorbuilder.md
  mip/develop/reference/class_mip_protectionprofile.md
  mip/develop/toc.yml
Labels: do-not-merge

#1017 From private repo
  Azure-RMSDocs/migrate-hsmkey-to-hsmkey.md
  Azure-RMSDocs/reports-aip.md
Labels: Change sent to author, analytics/subsvc, do-not-merge, information-protection/svc

#1018 From private repo
  Azure-RMSDocs/reports-aip.md
Labels: Change sent to author, analytics/subsvc, do-not-merge, information-protection/svc

#1019 From private repo
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1021 From private repo
  Azure-RMSDocs/byok-price-restrictions.md
  Azure-RMSDocs/toc.yml
Labels: do-not-merge

#1023 From private repo
  Azure-RMSDocs/quickstart-findsensitiveinfo.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md
  Azure-RMSDocs/what-is-information-protection.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1025 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/requirements-client-devices.md
  Azure-RMSDocs/rms-client/mobile-app-faq.md
Labels: Change sent to author, do-not-merge, information-protection/svc, prereqs/subsvc

#1026 From private repo
  Azure-RMSDocs/configure-adrms-restrictions.md
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/faqs-rms.md
  Azure-RMSDocs/migrate-from-ad-rms-phase4.md
  Azure-RMSDocs/office-apps-services-support.md
  Azure-RMSDocs/requirements-applications.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/aip-client.md
  Azure-RMSDocs/rms-client/aip-clientv2.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/client-classify-protect.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/upgrade-client-app.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v1client/subsvc

#1027 From private repo
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1029 From private repo
  Azure-RMSDocs/index.yml
Labels: do-not-merge, review-team-triage

#1031 Update how-does-it-work.md
  Azure-RMSDocs/how-does-it-work.md
Labels: Change sent to author, azurerms/subsvc, do-not-merge, information-protection/svc

#1030 Update how-does-it-work.md
  Azure-RMSDocs/how-does-it-work.md
Labels: Change sent to author, azurerms/subsvc, do-not-merge, information-protection/svc

#1033 From private repo
  Azure-RMSDocs/how-to-guides.md
  Azure-RMSDocs/infoprotect-oversharing-tutorial.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/manage-personal-data.md
  Azure-RMSDocs/monitor-rms-connector.md
  Azure-RMSDocs/prepare-environment-adrms.md
  Azure-RMSDocs/prepare.md
  Azure-RMSDocs/refresh-templates.md
  Azure-RMSDocs/requirements-azure-ad.md
  Azure-RMSDocs/rms-client/client-classify.md
  Azure-RMSDocs/rms-client/client-deployment-notes.md
  Azure-RMSDocs/rms-client/client-protection-only-mode.md
  Azure-RMSDocs/rms-client/client-remove-label-protection.md
  Azure-RMSDocs/rms-client/client-track-revoke.md
  Azure-RMSDocs/rms-client/client-user-guide.md
  Azure-RMSDocs/rms-client/client-view-use-files.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
  Azure-RMSDocs/rms-client/clientv2-user-guide.md
  Azure-RMSDocs/rms-client/clientv2-view-use-files.md
  Azure-RMSDocs/rms-client/configure-fci.md
  Azure-RMSDocs/rms-client/fci-script.md
  Azure-RMSDocs/rms-client/install-client-app.md
  Azure-RMSDocs/rms-client/sharing-app-windows.md
  Azure-RMSDocs/rms-connector-registry-settings.md
  Azure-RMSDocs/verify.md
  Azure-RMSDocs/what-is-information-protection.md
Labels: Change sent to author, azurerms/subsvc, do-not-merge, information-protection/svc
