Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2019-07, with the labels that each got.

#936 From private repo
  Azure-RMSDocs/deploy-aip-scanner-previousversions.md
  Azure-RMSDocs/deploy-aip-scanner.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#937 From private repo
  Azure-RMSDocs/configure-office365.md
  Azure-RMSDocs/configure-servers-rms-connector.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#938 From private repo
  Azure-RMSDocs/activate-azure.md
  Azure-RMSDocs/activate-office365.md
  Azure-RMSDocs/activate-service.md
  Azure-RMSDocs/administer-powershell.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/configure-policy-templates.md
  Azure-RMSDocs/configure-super-users.md
  Azure-RMSDocs/configure-templates-with-powershell.md
  Azure-RMSDocs/configure-usage-rights.md
  Azure-RMSDocs/decommission-deactivate.md
  Azure-RMSDocs/deploy-rms-connector.md
  Azure-RMSDocs/deployment-roadmap.md
  Azure-RMSDocs/develop/developing-your-application.md
  Azure-RMSDocs/develop/how-to-use-file-api-with-aadrm-cloud.md
  Azure-RMSDocs/develop/security-guidelines.md
  Azure-RMSDocs/faqs-rms.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/install-configure-rms-connector.md
  Azure-RMSDocs/install-powershell.md
  Azure-RMSDocs/log-analyze-usage.md
  Azure-RMSDocs/manage-personal-data.md
  Azure-RMSDocs/migrate-from-ad-rms-phase1.md
  Azure-RMSDocs/migrate-from-ad-rms-phase2.md
  Azure-RMSDocs/migrate-from-ad-rms-phase3.md
  Azure-RMSDocs/migrate-from-ad-rms-phase5.md
  Azure-RMSDocs/migrate-from-ad-rms-to-azure-rms.md
  Azure-RMSDocs/migrate-hsmkey-to-hsmkey.md
  Azure-RMSDocs/migrate-portal.md
  Azure-RMSDocs/migrate-softwarekey-to-hsmkey.md
  Azure-RMSDocs/migrate-softwarekey-to-softwarekey.md
  Azure-RMSDocs/monitor-rms-connector.md
  Azure-RMSDocs/operations-customer-managed-tenant-key.md
  Azure-RMSDocs/operations-microsoft-managed-tenant-key.md
  Azure-RMSDocs/plan-implement-tenant-key.md
  Azure-RMSDocs/prepare-environment-adrms.md
  Azure-RMSDocs/prepare.md
  Azure-RMSDocs/refresh-templates.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/client-deployment-notes.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md
  Azure-RMSDocs/rms-client/configure-fci.md
  Azure-RMSDocs/rms-client/upgrade-client-app.md
  Azure-RMSDocs/rms-connector-registry-settings.md
  Azure-RMSDocs/secure-collaboration-documents.md
  Azure-RMSDocs/terminology.md
  Azure-RMSDocs/toc.yml
  Azure-RMSDocs/verify.md
Labels: do-not-merge

#939 From private repo
  Azure-RMSDocs/activate-office365.md
  Azure-RMSDocs/administer-powershell.md
  Azure-RMSDocs/configure-applications.md
  Azure-RMSDocs/help-users.md
  Azure-RMSDocs/install-powershell.md
  Azure-RMSDocs/migrate-from-ad-rms-to-azure-rms.md
  Azure-RMSDocs/migrate-hsmkey-to-hsmkey.md
  Azure-RMSDocs/migrate-portal.md
  Azure-RMSDocs/migrate-softwarekey-to-hsmkey.md
  Azure-RMSDocs/migrate-softwarekey-to-softwarekey.md
  Azure-RMSDocs/refresh-templates.md
  Azure-RMSDocs/requirements-servers.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/client-deployment-notes.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
  Azure-RMSDocs/rms-connector-registry-settings.md
Labels: do-not-merge, information-protection/svc

#941 From private repo
  Azure-RMSDocs/install-powershell.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#943 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/deploy-rms-connector.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#944 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#945 From private repo
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#947 From private repo
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#949 From private repo
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/rms-client/aip-clientv2.md
  Azure-RMSDocs/rms-client/protected-pdf-readers.md
  Azure-RMSDocs/rms-client/use-client.md
  Azure-RMSDocs/terminology.md
  Azure-RMSDocs/what-is-azure-rms.md
  Azure-RMSDocs/what-is-information-protection.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#950 From private repo
  Azure-RMSDocs/compare-on-premise.md
  Azure-RMSDocs/compliance.md
  Azure-RMSDocs/configure-client.md
  Azure-RMSDocs/help-users.md
  Azure-RMSDocs/requirements-applications.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
  Azure-RMSDocs/rms-client/mobile-app-faq.md
  Azure-RMSDocs/rms-client/mobile-app-get-started.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#951 Fix double word `the`
  Azure-RMSDocs/requirements.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#952 From private repo
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#953 From private repo
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#956 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/requirements-client-devices.md
  Azure-RMSDocs/rms-client/sharing-app-windows.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#957 From private repo
  Azure-RMSDocs/infoprotect-oversharing-tutorial.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#959 From private repo
  Azure-RMSDocs/compare-on-premise.md
  Azure-RMSDocs/configure-policy-default.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/clientv2-classify-protect.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#960 From private repo
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#961 From private repo
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#962 From private repo
  Azure-RMSDocs/configure-exo-rules.md
  Azure-RMSDocs/configure-office365.md
  Azure-RMSDocs/configure-policy-add-remove-label.md
  Azure-RMSDocs/configure-policy-change-label.md
  Azure-RMSDocs/configure-policy-delete-reorder.md
  Azure-RMSDocs/configure-policy-languages.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy-new-label.md
  Azure-RMSDocs/includes/gdpr-intro-sentence.md
  Azure-RMSDocs/migrate-softwarekey-to-hsmkey.md
  Azure-RMSDocs/overview-policy.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/requirements-azure-ad.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-classify-protect.md
  Azure-RMSDocs/rms-client/client-classify.md
  Azure-RMSDocs/rms-client/client-protection-only-mode.md
  Azure-RMSDocs/rms-client/client-remove-label-protection.md
  Azure-RMSDocs/rms-client/client-track-revoke.md
  Azure-RMSDocs/rms-client/client-user-guide.md
  Azure-RMSDocs/rms-client/client-view-use-files.md
  Azure-RMSDocs/rms-client/clientv2-classify.md
  Azure-RMSDocs/rms-client/clientv2-remove-label-protection.md
  Azure-RMSDocs/rms-client/clientv2-user-guide.md
  Azure-RMSDocs/rms-client/clientv2-view-use-files.md
  Azure-RMSDocs/rms-client/fci-script.md
  Azure-RMSDocs/rms-client/install-client-app.md
  Azure-RMSDocs/rms-client/install-unifiedlabelingclient-app.md
  Azure-RMSDocs/rms-client/protected-pdf-readers.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#963 From private repo
  Azure-RMSDocs/aka.md
  Azure-RMSDocs/applications-support.md
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy-scope.md
  Azure-RMSDocs/configure-policy-settings.md
  Azure-RMSDocs/help-users.md
  Azure-RMSDocs/includes/gdpr-hybrid-note.md
  Azure-RMSDocs/infoprotect-settings-tutorial.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/quickstart-label-dnf-protectedemail.md
  Azure-RMSDocs/quickstart-viewpolicy.md
  Azure-RMSDocs/rms-client/protected-pdf-readers.md
  Azure-RMSDocs/what-is-azure-rms.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#964 From private repo
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#965 From private repo
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#967 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#968 From private repo
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#969 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#970 From private repo
  Azure-RMSDocs/rms-client/protected-pdf-readers.md
Labels: Change sent to author, do-not-merge, information-protection/svc
