Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2019-08, with the labels that each got.

#971 From private repo
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/faqs.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#973 From private repo
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/faqs-rms.md
  Azure-RMSDocs/office-apps-services-support.md
  Azure-RMSDocs/requirements-applications.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/client-classify-protect.md
  Azure-RMSDocs/rms-client/clientv2-classify-protect.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#975 From private repo
  Azure-RMSDocs/configure-adrms-restrictions.md
  Azure-RMSDocs/includes/gdpr-hybrid-note.md
  Azure-RMSDocs/includes/gdpr-intro-sentence.md
  Azure-RMSDocs/plan-implement-tenant-key.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: do-not-merge

#977 From private repo
  Azure-RMSDocs/configure-policy-settings.md
  Azure-RMSDocs/deploy-aip-scanner-previousversions.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#978 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/rms-client/aip-clientv2.md
  Azure-RMSDocs/rms-client/install-unifiedlabelingclient-app.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#979 From private repo
  Azure-RMSDocs/deploy-aip-scanner-previousversions.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/terminology.md
Labels: Change sent to author, do-not-merge, information-protection/svc, scanner/subsvc

#984 From private repo
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v1client/subsvc

#986 From private repo
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#987 From private repo
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/reports-aip.md
Labels: Change sent to author, analytics/subsvc, do-not-merge, information-protection/svc

#988 From private repo
  Azure-RMSDocs/media/certificate-checking.png
  Azure-RMSDocs/requirements.md
Labels: do-not-merge

#991 From private repo
  Azure-RMSDocs/faqs.md
Labels: do-not-merge

#992 Update release-notes-rtm.md
  Azure-RMSDocs/develop/release-notes-rtm.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#994 Update release-notes-rtm.md
  Azure-RMSDocs/develop/release-notes-rtm.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, information-protection/svc

#997 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/protected-pdf-readers-android.md
  Azure-RMSDocs/rms-client/protected-pdf-readers-ios.md
  Azure-RMSDocs/rms-client/protected-pdf-readers-mac.md
  Azure-RMSDocs/rms-client/protected-pdf-readers-windows.md
  Azure-RMSDocs/rms-client/protected-pdf-readers.md
  Azure-RMSDocs/toc.yml
Labels: do-not-merge

#998 From private repo
  Azure-RMSDocs/compare-on-premise.md
  Azure-RMSDocs/install-configure-rms-connector.md
  Azure-RMSDocs/operations-microsoft-managed-tenant-key.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  mip/develop/toc.yml
Labels: do-not-merge

#1000 From private repo
  Azure-RMSDocs/install-powershell.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1001 From private repo
  Azure-RMSDocs/operations-customer-managed-tenant-key.md
Labels: Change sent to author, do-not-merge, information-protection/svc, kms/subsvc

#1003 From private repo
  Azure-RMSDocs/deploy-aip-scanner-previousversions.md
  Azure-RMSDocs/deploy-aip-scanner.md
Labels: Change sent to author, do-not-merge, information-protection/svc, scanner/subsvc

#1004 From private repo
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1005 From private repo
  Azure-RMSDocs/rms-client/aip-clientv2.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc
