Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2020-07, with the labels that each got.

#1208 From private repo
  Azure-RMSDocs/configure-office-apps.md
  Azure-RMSDocs/configure-office365.md
  Azure-RMSDocs/configure-super-users.md
  Azure-RMSDocs/configure-templates-with-powershell.md
  Azure-RMSDocs/configure-usage-rights.md
  Azure-RMSDocs/decommission-deactivate.md
  Azure-RMSDocs/deploy-aip-scanner-classic.md
  Azure-RMSDocs/file-server-support.md
  Azure-RMSDocs/help-users.md
  Azure-RMSDocs/how-does-it-work.md
  Azure-RMSDocs/how-to-guides.md
  Azure-RMSDocs/install-configure-rms-connector.md
  Azure-RMSDocs/install-powershell.md
  Azure-RMSDocs/log-analyze-usage.md
  Azure-RMSDocs/manage-personal-data.md
  Azure-RMSDocs/migrate-softwarekey-to-hsmkey.md
  Azure-RMSDocs/migrate-softwarekey-to-softwarekey.md
  Azure-RMSDocs/monitor-rms-connector.md
  Azure-RMSDocs/office-apps-services-support.md
  Azure-RMSDocs/operations-customer-managed-tenant-key.md
  Azure-RMSDocs/operations-microsoft-managed-tenant-key.md
  Azure-RMSDocs/operations-tenant-key.md
  Azure-RMSDocs/overview-policy.md
  Azure-RMSDocs/plan-implement-tenant-key.md
  Azure-RMSDocs/prepare-environment-adrms.md
  Azure-RMSDocs/requirements-applications.md
  Azure-RMSDocs/requirements-azure-ad.md
  Azure-RMSDocs/requirements-servers.md
  Azure-RMSDocs/rms-client/use-client.md
  Azure-RMSDocs/rms-connector-registry-settings.md
  Azure-RMSDocs/rms-for-individuals.md
  Azure-RMSDocs/terminology.md
  Azure-RMSDocs/what-is-azure-rms.md
Labels: do-not-merge

#1212 From private repo
  Azure-RMSDocs/media/edge_open_browser.png
  Azure-RMSDocs/rms-client/protected-pdf-readers-mac.md
  Azure-RMSDocs/rms-client/protected-pdf-readers-windows.md
  Azure-RMSDocs/rms-client/protected-pdf-readers.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1213 From private repo
  Azure-RMSDocs/audit-logs.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1214 From private repo
  Azure-RMSDocs/byok-price-restrictions.md
  Azure-RMSDocs/configure-adrms-restrictions.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/known-issues.md
  Azure-RMSDocs/media/client-viewer-stretched-images.PNG
  Azure-RMSDocs/migrate-from-ad-rms-to-azure-rms.md
  Azure-RMSDocs/office-apps-services-support.md
  Azure-RMSDocs/prepare-environment-adrms.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md
  Azure-RMSDocs/toc.yml
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1215 From private repo
  Azure-RMSDocs/byok-price-restrictions.md
  Azure-RMSDocs/configure-adrms-restrictions.md
  Azure-RMSDocs/get-started-tenant-root-keys.md
  Azure-RMSDocs/media/no-icon.png
  Azure-RMSDocs/media/videos-gifs/dke.gif
  Azure-RMSDocs/media/yes-icon.png
  Azure-RMSDocs/operations-customer-managed-tenant-key.md
  Azure-RMSDocs/operations-microsoft-managed-tenant-key.md
  Azure-RMSDocs/plan-implement-tenant-key.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/toc.yml
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1061 Improve code samples
  Azure-RMSDocs/develop/authentication-integration.md
  Azure-RMSDocs/develop/enabling-logging.md
  Azure-RMSDocs/develop/file-api-configuration.md
  Azure-RMSDocs/develop/how-to-enable-email-notification.md
  Azure-RMSDocs/develop/ios-os-x-code-examples.md
  Azure-RMSDocs/develop/linux-c-code-examples.md
  Azure-RMSDocs/develop/tracking-content.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, information-protection/svc

#1218 From private repo
  mip/develop/quick-email-msg-csharp.md
  mip/develop/quick-file-justify-actions-cpp.md
Labels: do-not-merge

#1221 From private repo
  Azure-RMSDocs/active-directory-rights-manage-mobile-device.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1206 Minor update for PowerBI preview
  Azure-RMSDocs/faqs.md
Labels: Change sent to author, aq-pr-triaged, information-protection/svc, ready-to-merge

#1207 Minor update about native labeling in Offine Online
  Azure-RMSDocs/configure-policy-protection.md
Labels: Change sent to author, aiplabels/subsvc, aq-pr-triaged, information-protection/svc, ready-to-merge

#1224 Remove Preview mentions that are now GA
  Azure-RMSDocs/configure-policy-migrate-labels.md
Labels: Change sent to author, information-protection/svc, labelmigrate/subsvc, ready-to-merge

#1195 Sensitivity labels in OWA are GA, Message Classification section needs to only cover Exchange Server
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
Labels: Change sent to author, aq-pr-triaged, information-protection/svc, ready-to-merge, v1client/subsvc

#1225 From private repo
  Azure-RMSDocs/known-issues.md
  mip/develop/concept-mip-proxies.md
  mip/develop/toc.yml
Labels: Change sent to author, do-not-merge, information-protection/svc
