Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2020-01, with the labels that each got.

#1095 From private repo
  Azure-RMSDocs/activate-azure.md
  Azure-RMSDocs/configure-adrms-restrictions.md
  Azure-RMSDocs/configure-client.md
  Azure-RMSDocs/configure-exo-rules.md
  Azure-RMSDocs/configure-policy-add-remove-label.md
  Azure-RMSDocs/configure-policy-change-label.md
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/configure-policy-default.md
  Azure-RMSDocs/configure-policy-delete-reorder.md
  Azure-RMSDocs/configure-policy-languages.md
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy-new-label.md
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/configure-policy-scope.md
  Azure-RMSDocs/configure-policy-settings.md
  Azure-RMSDocs/configure-policy-templates.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/faqs-rms.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/infoprotect-oversharing-tutorial.md
  Azure-RMSDocs/infoprotect-quick-start-tutorial.md
  Azure-RMSDocs/infoprotect-settings-tutorial.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/migrate-portal.md
  Azure-RMSDocs/quickstart-label-dnf-protectedemail.md
  Azure-RMSDocs/quickstart-label-specificusers.md
  Azure-RMSDocs/refresh-templates.md
  Azure-RMSDocs/rms-client/aip-client.md
  Azure-RMSDocs/rms-client/aip-clientv2.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/client-classify-protect.md
  Azure-RMSDocs/rms-client/client-classify.md
  Azure-RMSDocs/rms-client/client-deployment-notes.md
  Azure-RMSDocs/rms-client/client-protection-only-mode.md
  Azure-RMSDocs/rms-client/client-remove-label-protection.md
  Azure-RMSDocs/rms-client/client-track-revoke.md
  Azure-RMSDocs/rms-client/client-user-guide.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/client-view-use-files.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/use-client.md
  Azure-RMSDocs/secure-collaboration-documents.md
Labels: do-not-merge

#1096 From private repo
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1098 From private repo
  Azure-RMSDocs/activate-azure.md
  Azure-RMSDocs/configure-adrms-restrictions.md
  Azure-RMSDocs/configure-client.md
  Azure-RMSDocs/configure-exo-rules.md
  Azure-RMSDocs/configure-policy-add-remove-label.md
  Azure-RMSDocs/configure-policy-change-label.md
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/configure-policy-default.md
  Azure-RMSDocs/configure-policy-delete-reorder.md
  Azure-RMSDocs/configure-policy-languages.md
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy-new-label.md
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/configure-policy-scope.md
  Azure-RMSDocs/configure-policy-settings.md
  Azure-RMSDocs/configure-policy-templates.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/faqs-rms.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/infoprotect-oversharing-tutorial.md
  Azure-RMSDocs/infoprotect-quick-start-tutorial.md
  Azure-RMSDocs/infoprotect-settings-tutorial.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/migrate-portal.md
  Azure-RMSDocs/quickstart-label-dnf-protectedemail.md
  Azure-RMSDocs/quickstart-label-specificusers.md
  Azure-RMSDocs/refresh-templates.md
  Azure-RMSDocs/rms-client/aip-client.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
  Azure-RMSDocs/secure-collaboration-documents.md
Labels: Change sent to author, aiplabels/subsvc, do-not-merge, information-protection/svc

#1099 From private repo
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1100 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/requirements-client-devices.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/mobile-app-faq.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v1client/subsvc

#1101 From private repo
  Azure-RMSDocs/configure-usage-rights.md
Labels: Change sent to author, azurerms/subsvc, do-not-merge, information-protection/svc

#1102 From private repo
  Azure-RMSDocs/refresh-templates.md
Labels: Change sent to author, azurerms/subsvc, do-not-merge, information-protection/svc

#1103 From private repo
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/media/aip-quick-set-site-permissions.png
  Azure-RMSDocs/media/aip-quick-set-sp-permissions.png
  Azure-RMSDocs/media/aip-quick-set-user-permissions.png
  Azure-RMSDocs/media/scanner-stop-scan.png
  Azure-RMSDocs/quickstart-findsensitiveinfo.md
  Azure-RMSDocs/refresh-templates.md
  Azure-RMSDocs/rms-client/aip-client.md
  Azure-RMSDocs/rms-client/aip-clientv2.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/client-classify-protect.md
  Azure-RMSDocs/rms-client/client-classify.md
  Azure-RMSDocs/rms-client/client-deployment-notes.md
  Azure-RMSDocs/rms-client/client-protection-only-mode.md
  Azure-RMSDocs/rms-client/client-remove-label-protection.md
  Azure-RMSDocs/rms-client/client-track-revoke.md
  Azure-RMSDocs/rms-client/client-user-guide.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/client-view-use-files.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
  Azure-RMSDocs/rms-client/clientv2-classify-protect.md
  Azure-RMSDocs/rms-client/clientv2-classify.md
  Azure-RMSDocs/rms-client/clientv2-remove-label-protection.md
  Azure-RMSDocs/rms-client/clientv2-user-guide.md
  Azure-RMSDocs/rms-client/clientv2-view-use-files.md
  Azure-RMSDocs/rms-client/install-client-app.md
  Azure-RMSDocs/rms-client/install-unifiedlabelingclient-app.md
  Azure-RMSDocs/rms-client/mobile-app-get-started.md
  Azure-RMSDocs/rms-client/protected-pdf-readers-windows.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
  Azure-RMSDocs/secure-collaboration-documents.md
Labels: Change sent to author, aiplabels/subsvc, do-not-merge, information-protection/svc

#1105 From private repo
  Azure-RMSDocs/configure-servers-rms-connector.md
  Azure-RMSDocs/deploy-rms-connector.md
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/install-configure-rms-connector.md
  Azure-RMSDocs/migrate-from-ad-rms-to-azure-rms.md
  Azure-RMSDocs/migrate-hsmkey-to-hsmkey.md
  Azure-RMSDocs/monitor-rms-connector.md
  Azure-RMSDocs/requirements-servers.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/aip-client.md
  Azure-RMSDocs/rms-client/aip-clientv2.md
  Azure-RMSDocs/rms-client/client-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/client-deployment-notes.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/upgrade-client-app.md
  Azure-RMSDocs/rms-client/use-client.md
  Azure-RMSDocs/rms-connector-registry-settings.md
Labels: Change sent to author, connector/subsvc, do-not-merge, information-protection/svc

#1107 From private repo
  Azure-RMSDocs/configure-policy-languages.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: do-not-merge

#1108 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
Labels: Change sent to author, do-not-merge, information-protection/svc, labelmigrate/subsvc

#1111 From private repo
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/media/migration-status-banner.png
  Azure-RMSDocs/rms-client/use-client.md
Labels: do-not-merge
