Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2020-12, with the labels that each got.

#1308 From private repo
  Azure-RMSDocs/configure-servers-rms-connector.md
  Azure-RMSDocs/deploy-aip-scanner-configure-install.md
  Azure-RMSDocs/deploy-aip-scanner-prereqs.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/develop/developing-your-application.md
  Azure-RMSDocs/media/ul-scanner-arch.png
  Azure-RMSDocs/migrate-from-ad-rms-phase1.md
  Azure-RMSDocs/migrate-from-ad-rms-phase4.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  mip/develop/quick-email-msg-cpp.md
  mip/develop/quick-email-msg-csharp.md
  mip/develop/quick-file-justify-actions-cpp.md
  mip/develop/quick-file-justify-actions-csharp.md
  mip/develop/quick-file-list-labels-cpp.md
  mip/develop/quick-file-list-labels-csharp.md
  mip/develop/quick-file-republishing-cpp.md
  mip/develop/quick-file-republishing-csharp.md
  mip/develop/quick-protection-app-initialization-cpp.md
  mip/develop/quick-protection-app-initialization-csharp.md
  mip/develop/quick-protection-encrypt-decrypt-text-cpp.md
  mip/develop/quick-protection-encrypt-decrypt-text-csharp.md
  mip/develop/quick-protection-list-templates-cpp.md
  mip/develop/quick-protection-list-templates-csharp.md
  mip/develop/reference/struct_mip_applicationinfo.md
  mip/develop/reference/struct_mip_telemetryconfiguration.md
  mip/develop/setup-configure-mip.md
Labels: do-not-merge

#1310 From private repo
  Azure-RMSDocs/deploy-aip-scanner-prereqs.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  mip/develop/quick-app-initialization-cpp.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1248 Fix compilation error
  mip/develop/quick-file-set-get-label-csharp.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, information-protection/svc

#1313 From private repo
  Azure-RMSDocs/configure-client.md
  Azure-RMSDocs/configure-usage-rights.md
  Azure-RMSDocs/deploy-aip-scanner-prereqs.md
  Azure-RMSDocs/develop/release-notes.md
  Azure-RMSDocs/faqs-rms.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/infoprotect-quick-start-tutorial.md
  Azure-RMSDocs/infoprotect-settings-tutorial.md
  Azure-RMSDocs/quickstart-label-dnf-protectedemail.md
  Azure-RMSDocs/requirements-applications.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: do-not-merge
