Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2020-06, with the labels that each got.

#1184 Incorrect key name (Set-labelpolicy is not the key name, it's the com…
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1185 From private repo
  Azure-RMSDocs/audit-logs.md
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/office-apps-services-support.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/client-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/protected-pdf-readers.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
  Azure-RMSDocs/toc.yml
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1186 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
Labels: Change sent to author, do-not-merge, information-protection/svc, scanner/subsvc

#1187 From private repo
  mip/develop/concept-email-cpp.md
  mip/develop/concept-justification-cpp.md
  mip/develop/concept-republishing-cpp.md
  mip/develop/media/justify-action.png
  mip/develop/quick-email-msg-cpp.md
  mip/develop/quick-email-msg-csharp.md
  mip/develop/quick-file-justify-actions-cpp.md
  mip/develop/quick-file-justify-actions-csharp.md
  mip/develop/quick-file-republishing-cpp.md
  mip/develop/quick-file-republishing-csharp.md
  mip/develop/toc.yml
Labels: Change sent to author, do-not-merge, information-protection/svc

#1188 Improved wording removing a grammar error
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1192 From private repo
  Azure-RMSDocs/audit-logs.md
  Azure-RMSDocs/compare-on-premise.md
  Azure-RMSDocs/configure-adrms-restrictions.md
  Azure-RMSDocs/configure-office365.md
  Azure-RMSDocs/configure-policy-scope.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/deploy-rms-connector.md
  Azure-RMSDocs/deployment-roadmap.md
  Azure-RMSDocs/develop/deprecation-notice.md
  Azure-RMSDocs/faqs-rms.md
  Azure-RMSDocs/infoprotect-oversharing-tutorial.md
  Azure-RMSDocs/infoprotect-quick-start-tutorial.md
  Azure-RMSDocs/infoprotect-settings-tutorial.md
  Azure-RMSDocs/information-support.md
  Azure-RMSDocs/office-apps-services-support.md
  Azure-RMSDocs/quickstart-findsensitiveinfo.md
  Azure-RMSDocs/quickstart-label-dnf-protectedemail.md
  Azure-RMSDocs/quickstart-label-specificusers.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/rms-client/aip-clientv2.md
  Azure-RMSDocs/rms-client/client-admin-guide-document-tracking.md
  Azure-RMSDocs/rms-client/client-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/client-admin-guide-install.md
  Azure-RMSDocs/rms-client/client-admin-guide.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide.md
  Azure-RMSDocs/rms-client/clientv2-classify-protect.md
  Azure-RMSDocs/rms-client/clientv2-classify.md
  Azure-RMSDocs/rms-client/clientv2-remove-label-protection.md
  Azure-RMSDocs/rms-client/clientv2-user-guide.md
  Azure-RMSDocs/rms-client/clientv2-view-use-files.md
  Azure-RMSDocs/rms-client/install-unifiedlabelingclient-app.md
  Azure-RMSDocs/what-is-information-protection.md
Labels: do-not-merge

#1193 From private repo
  Azure-RMSDocs/active-directory-rights-manage-mobile-device.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1197 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/develop/deprecation-notice.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc, scanner/subsvc

#1201 From private repo
  Azure-RMSDocs/audit-logs.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  mip/develop/index.yml
  mip/index.yml
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc
