Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2020-02, with the labels that each got.

#1113 From private repo
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1114 From private repo
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1115 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1116 From private repo
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/client-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v1client/subsvc

#1119 From private repo
  Azure-RMSDocs/configure-policy-classification.md
  Azure-RMSDocs/configure-policy-default.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/configure-policy-settings.md
  Azure-RMSDocs/configure-policy.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/deployment-roadmap.md
  Azure-RMSDocs/faqs-infoprotect.md
  Azure-RMSDocs/faqs.md
  Azure-RMSDocs/infoprotect-quick-start-tutorial.md
  Azure-RMSDocs/infoprotect-settings-tutorial.md
  Azure-RMSDocs/overview-policy.md
  Azure-RMSDocs/quickstart-label-dnf-protectedemail.md
  Azure-RMSDocs/quickstart-label-specificusers.md
  Azure-RMSDocs/quickstart-viewpolicy.md
  Azure-RMSDocs/rms-client/clientv2-classify-protect.md
  Azure-RMSDocs/rms-client/clientv2-classify.md
  Azure-RMSDocs/rms-client/clientv2-remove-label-protection.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1122 Added missing word
  Azure-RMSDocs/migrate-from-ad-rms-to-azure-rms.md
Labels: Change sent to author, assessing_(C&L), information-protection/svc, migration/subsvc, ready-to-merge

#1123 From private repo
  Azure-RMSDocs/configure-servers-rms-connector.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1124 From private repo
  mip/develop/toc.yml
  mip/develop/version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1126 From private repo
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1129 From private repo
  Azure-RMSDocs/configure-policy-markings.md
  Azure-RMSDocs/configure-policy-protection.md
  Azure-RMSDocs/deploy-aip-scanner.md
  Azure-RMSDocs/faqs-rms.md
Labels: Change sent to author, do-not-merge, information-protection/svc, scanner/subsvc
