Repository MicrosoftDocs/Azure-RMSDocs, pull requests merged in 2020-10, with the labels that each got.

#1269 Typo "～adams@contoso.com**"→"adams\@contoso.com**"
  Azure-RMSDocs/configure-office365.md
Labels: Change sent to author, azurerms/subsvc, do-not-merge, information-protection/svc

#1271 From private repo
  Azure-RMSDocs/deploy-aip-scanner-configure-install.md
  Azure-RMSDocs/deploy-aip-scanner-manage.md
  Azure-RMSDocs/deploy-aip-scanner-prereqs.md
  Azure-RMSDocs/deployment-roadmap-protect-only.md
  Azure-RMSDocs/reports-aip.md
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md
Labels: Change sent to author, do-not-merge, information-protection/svc, v2client/subsvc

#1273 From private repo
  mip/includes/mip-sdk-platform-support.md
Labels: Change sent to author, do-not-merge, information-protection/svc

#1294 From private repo
  Azure-RMSDocs/activate-office365.md
  Azure-RMSDocs/configure-exo-rules.md
  Azure-RMSDocs/configure-policy-migrate-labels.md
  Azure-RMSDocs/deploy-aip-scanner-prereqs-classic.md
  Azure-RMSDocs/deploy-aip-scanner-prereqs.md
  Azure-RMSDocs/develop/deprecation-notice.md
  Azure-RMSDocs/media/ios-share-to-aip-viewer.png
  Azure-RMSDocs/requirements.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md
  Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md
  Azure-RMSDocs/rms-client/mobile-app-faq.md
  Azure-RMSDocs/rms-client/protected-pdf-readers.md
  Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md
  Azure-RMSDocs/rms-client/use-client.md
  mip/develop/concept-mipcontext.md
  mip/develop/concept-profile-engine-cpp.md
  mip/develop/quick-app-initialization-csharp.md
Labels: do-not-merge
